import { createElement } from 'lwc';
import EDF91_EnggList_Instructions from 'c/eDF91_EnggList_Instructions';

describe('c-e-d-f-91-engg-list-instructions', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-e-d-f-91-engg-list-instructions', {
            is: EDF91_EnggList_Instructions
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});